export const FETCH_TV_REQUEST = 'FETCH_TV_REQUEST'
export const FETCH_TV_SUCCESS = 'FETCH_TV_SUCCESS'
export const FETCH_TV_ERROR = 'FETCH_TV_ERROR'
export const FETCH_TV_LIST_SUCCESS = 'FETCH_TV_LIST_SUCCESS'